export const FETCH_IMAGES = 'FETCH_IMAGES'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'

export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_ALL_SUCCESS = 'FETCH_ALL_SUCCESS'
export const FETCH_ALL_FAILURE = 'FETCH_ALL_FAILURE'

export const ADD_TO_FVT='ADD_TO_FVT'
export const ADD_SUCCESS='ADD_SUCCESS'

export const REMOVE_FVT='REMOVE_FVT'
export const REMOVE_SUCCESS='REMOVE_SUCCESS'